BEGIN;

-- Governance tables anchor provenance and data quality across all downstream facts.
CREATE TABLE IF NOT EXISTS data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_data_sources_source_code UNIQUE (source_code)
);

COMMENT ON TABLE data_sources IS '数据源主表，记录 Anne 主库使用的外部或内部数据提供方。';
COMMENT ON COLUMN data_sources.id IS '数据源主键。';
COMMENT ON COLUMN data_sources.source_code IS '数据源编码，库内唯一。';
COMMENT ON COLUMN data_sources.source_name IS '数据源名称。';
COMMENT ON COLUMN data_sources.source_type IS '数据源类型，例如 market、financial、macro、news。';
COMMENT ON COLUMN data_sources.description IS '数据源补充说明。';
COMMENT ON COLUMN data_sources.metadata IS '数据源扩展元数据，使用 JSONB 存储。';
COMMENT ON COLUMN data_sources.created_at IS '记录创建时间。';
COMMENT ON COLUMN data_sources.updated_at IS '记录更新时间。';

CREATE TABLE IF NOT EXISTS ingestion_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_key TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    row_count INTEGER,
    error_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_ingestion_batches_source_batch_key UNIQUE (source_id, batch_key)
);

COMMENT ON TABLE ingestion_batches IS '入库批次表，记录每次采集或标准化入库任务的批次信息。';
COMMENT ON COLUMN ingestion_batches.id IS '入库批次主键。';
COMMENT ON COLUMN ingestion_batches.source_id IS '关联的数据源主键。';
COMMENT ON COLUMN ingestion_batches.batch_key IS '批次业务标识，同一数据源下唯一。';
COMMENT ON COLUMN ingestion_batches.status IS '批次状态，例如 pending、completed、failed。';
COMMENT ON COLUMN ingestion_batches.started_at IS '批次开始时间。';
COMMENT ON COLUMN ingestion_batches.completed_at IS '批次完成时间。';
COMMENT ON COLUMN ingestion_batches.row_count IS '批次处理的记录数。';
COMMENT ON COLUMN ingestion_batches.error_count IS '批次错误数。';
COMMENT ON COLUMN ingestion_batches.notes IS '批次备注。';
COMMENT ON COLUMN ingestion_batches.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN ingestion_batches.created_at IS '记录创建时间。';
COMMENT ON COLUMN ingestion_batches.updated_at IS '记录更新时间。';

CREATE TABLE IF NOT EXISTS quality_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES ingestion_batches(id) ON DELETE CASCADE,
    check_name TEXT NOT NULL,
    check_status TEXT NOT NULL,
    severity TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_quality_checks_batch_check_name_checked_at UNIQUE (batch_id, check_name, checked_at)
);

COMMENT ON TABLE quality_checks IS '质量检查表，记录批次级数据校验结果。';
COMMENT ON COLUMN quality_checks.id IS '质量检查主键。';
COMMENT ON COLUMN quality_checks.batch_id IS '关联的入库批次主键。';
COMMENT ON COLUMN quality_checks.check_name IS '检查项名称。';
COMMENT ON COLUMN quality_checks.check_status IS '检查结果状态，例如 passed、failed。';
COMMENT ON COLUMN quality_checks.severity IS '问题严重级别。';
COMMENT ON COLUMN quality_checks.details IS '质量检查详细结果，使用 JSONB 存储。';
COMMENT ON COLUMN quality_checks.checked_at IS '执行检查的时间。';
COMMENT ON COLUMN quality_checks.created_at IS '记录创建时间。';

-- Core entity table for tradable instruments and macro-linked assets.
CREATE TABLE IF NOT EXISTS instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    instrument_name TEXT,
    instrument_type TEXT NOT NULL,
    currency TEXT,
    status TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_instruments_exchange_symbol UNIQUE (exchange, symbol)
);

COMMENT ON TABLE instruments IS '标的维表，记录证券、指数或其他可分析对象的基础信息。';
COMMENT ON COLUMN instruments.id IS '标的主键。';
COMMENT ON COLUMN instruments.source_id IS '来源数据源主键。';
COMMENT ON COLUMN instruments.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN instruments.exchange IS '交易所或市场代码。';
COMMENT ON COLUMN instruments.symbol IS '标的代码。';
COMMENT ON COLUMN instruments.instrument_name IS '标的名称。';
COMMENT ON COLUMN instruments.instrument_type IS '标的类型，例如 equity、index、fund。';
COMMENT ON COLUMN instruments.currency IS '计价币种。';
COMMENT ON COLUMN instruments.status IS '标的状态，例如 active、delisted。';
COMMENT ON COLUMN instruments.metadata IS '标的扩展属性，使用 JSONB 存储。';
COMMENT ON COLUMN instruments.ingested_at IS '入库时间。';
COMMENT ON COLUMN instruments.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN instruments.version IS '版本号，用于保留多版本标准化结果。';
COMMENT ON COLUMN instruments.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN instruments.created_at IS '记录创建时间。';
COMMENT ON COLUMN instruments.updated_at IS '记录更新时间。';

-- Governance columns are repeated across fact tables on purpose so loaders and audits
-- can use a stable lineage contract regardless of domain-specific business fields.
CREATE TABLE IF NOT EXISTS market_bars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    timeframe TEXT NOT NULL,
    adjustment_type TEXT NOT NULL DEFAULT 'none',
    bar_time TIMESTAMPTZ NOT NULL,
    open_price NUMERIC(20, 6),
    high_price NUMERIC(20, 6),
    low_price NUMERIC(20, 6),
    close_price NUMERIC(20, 6),
    volume NUMERIC(24, 6),
    turnover NUMERIC(24, 6),
    trade_count BIGINT,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_market_bars_business_key UNIQUE (instrument_id, bar_time, timeframe, adjustment_type, version)
);

COMMENT ON TABLE market_bars IS '行情 K 线事实表，存储按时间粒度标准化后的 OHLCV 数据。';
COMMENT ON COLUMN market_bars.id IS '行情记录主键。';
COMMENT ON COLUMN market_bars.source_id IS '来源数据源主键。';
COMMENT ON COLUMN market_bars.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN market_bars.instrument_id IS '关联标的主键。';
COMMENT ON COLUMN market_bars.timeframe IS '时间粒度，例如 1d、1h、5m。';
COMMENT ON COLUMN market_bars.adjustment_type IS '复权类型，例如 none、forward、backward。';
COMMENT ON COLUMN market_bars.bar_time IS 'K 线时点，通常表示该 bar 的结束时间。';
COMMENT ON COLUMN market_bars.open_price IS '开盘价。';
COMMENT ON COLUMN market_bars.high_price IS '最高价。';
COMMENT ON COLUMN market_bars.low_price IS '最低价。';
COMMENT ON COLUMN market_bars.close_price IS '收盘价。';
COMMENT ON COLUMN market_bars.volume IS '成交量。';
COMMENT ON COLUMN market_bars.turnover IS '成交额。';
COMMENT ON COLUMN market_bars.trade_count IS '成交笔数。';
COMMENT ON COLUMN market_bars.ingested_at IS '入库时间。';
COMMENT ON COLUMN market_bars.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN market_bars.version IS '版本号，用于保留重复清洗后的多版本结果。';
COMMENT ON COLUMN market_bars.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN market_bars.created_at IS '记录创建时间。';

-- Financial reports stay as a normalized metadata + JSON metrics table in v1 to avoid
-- prematurely splitting statements into multiple schemas before real ingestion patterns settle.
CREATE TABLE IF NOT EXISTS financial_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    statement_type TEXT NOT NULL,
    period_type TEXT NOT NULL,
    report_period_end DATE NOT NULL,
    announced_at TIMESTAMPTZ,
    currency TEXT,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_financial_reports_business_key UNIQUE (instrument_id, report_period_end, statement_type, version)
);

COMMENT ON TABLE financial_reports IS '财报事实表，使用统一元数据列加 JSONB 指标承接不同报表类型。';
COMMENT ON COLUMN financial_reports.id IS '财报记录主键。';
COMMENT ON COLUMN financial_reports.source_id IS '来源数据源主键。';
COMMENT ON COLUMN financial_reports.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN financial_reports.instrument_id IS '关联标的主键。';
COMMENT ON COLUMN financial_reports.statement_type IS '报表类型，例如 income_statement、balance_sheet、cash_flow。';
COMMENT ON COLUMN financial_reports.period_type IS '报告周期类型，例如 annual、quarterly。';
COMMENT ON COLUMN financial_reports.report_period_end IS '报告期结束日期。';
COMMENT ON COLUMN financial_reports.announced_at IS '公告发布时间。';
COMMENT ON COLUMN financial_reports.currency IS '报表金额币种。';
COMMENT ON COLUMN financial_reports.metrics IS '标准化后的财务指标集合，使用 JSONB 存储。';
COMMENT ON COLUMN financial_reports.ingested_at IS '入库时间。';
COMMENT ON COLUMN financial_reports.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN financial_reports.version IS '版本号，用于保留修订版或重复清洗结果。';
COMMENT ON COLUMN financial_reports.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN financial_reports.created_at IS '记录创建时间。';

-- Macro series metadata is separated from observations so time-series facts can keep
-- a clean uniqueness rule and can later be upgraded to hypertables independently.
CREATE TABLE IF NOT EXISTS macro_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    series_code TEXT NOT NULL,
    series_name TEXT NOT NULL,
    frequency TEXT NOT NULL,
    region_code TEXT,
    unit TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_macro_series_series_code UNIQUE (series_code)
);

COMMENT ON TABLE macro_series IS '宏观指标定义表，记录序列本身的元数据。';
COMMENT ON COLUMN macro_series.id IS '宏观序列主键。';
COMMENT ON COLUMN macro_series.source_id IS '来源数据源主键。';
COMMENT ON COLUMN macro_series.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN macro_series.series_code IS '宏观序列编码，库内唯一。';
COMMENT ON COLUMN macro_series.series_name IS '宏观序列名称。';
COMMENT ON COLUMN macro_series.frequency IS '发布频率，例如 daily、monthly、quarterly。';
COMMENT ON COLUMN macro_series.region_code IS '地区或国家代码。';
COMMENT ON COLUMN macro_series.unit IS '指标单位。';
COMMENT ON COLUMN macro_series.metadata IS '序列扩展元数据，使用 JSONB 存储。';
COMMENT ON COLUMN macro_series.ingested_at IS '入库时间。';
COMMENT ON COLUMN macro_series.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN macro_series.version IS '版本号。';
COMMENT ON COLUMN macro_series.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN macro_series.created_at IS '记录创建时间。';
COMMENT ON COLUMN macro_series.updated_at IS '记录更新时间。';

CREATE TABLE IF NOT EXISTS macro_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    series_id BIGINT NOT NULL REFERENCES macro_series(id) ON DELETE CASCADE,
    observation_time TIMESTAMPTZ NOT NULL,
    observation_value NUMERIC(24, 8),
    observation_text TEXT,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_macro_observations_business_key UNIQUE (series_id, observation_time, version)
);

COMMENT ON TABLE macro_observations IS '宏观指标观测表，记录宏观序列在每个时点的取值。';
COMMENT ON COLUMN macro_observations.id IS '宏观观测记录主键。';
COMMENT ON COLUMN macro_observations.source_id IS '来源数据源主键。';
COMMENT ON COLUMN macro_observations.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN macro_observations.series_id IS '关联宏观序列主键。';
COMMENT ON COLUMN macro_observations.observation_time IS '观测时点。';
COMMENT ON COLUMN macro_observations.observation_value IS '数值型观测值。';
COMMENT ON COLUMN macro_observations.observation_text IS '文本型观测值或补充说明。';
COMMENT ON COLUMN macro_observations.ingested_at IS '入库时间。';
COMMENT ON COLUMN macro_observations.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN macro_observations.version IS '版本号。';
COMMENT ON COLUMN macro_observations.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN macro_observations.created_at IS '记录创建时间。';

-- Documents cover both news and research reports in v1; document_type keeps the model
-- extensible without forcing an early table split.
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    instrument_id BIGINT REFERENCES instruments(id),
    document_type TEXT NOT NULL,
    external_id TEXT,
    title TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    language_code TEXT,
    sentiment_label TEXT,
    summary TEXT,
    source_url TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE documents IS '文档表，统一承接新闻、研报、公告等文本型或文档型元数据。';
COMMENT ON COLUMN documents.id IS '文档主键。';
COMMENT ON COLUMN documents.source_id IS '来源数据源主键。';
COMMENT ON COLUMN documents.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN documents.instrument_id IS '关联标的主键，可为空，表示文档不只针对单一标的。';
COMMENT ON COLUMN documents.document_type IS '文档类型，例如 news、research_report、announcement。';
COMMENT ON COLUMN documents.external_id IS '外部系统中的文档唯一标识。';
COMMENT ON COLUMN documents.title IS '文档标题。';
COMMENT ON COLUMN documents.published_at IS '文档发布时间。';
COMMENT ON COLUMN documents.language_code IS '文档语言代码。';
COMMENT ON COLUMN documents.sentiment_label IS '情绪标签。';
COMMENT ON COLUMN documents.summary IS '文档摘要。';
COMMENT ON COLUMN documents.source_url IS '文档来源链接。';
COMMENT ON COLUMN documents.metadata IS '文档扩展元数据，使用 JSONB 存储。';
COMMENT ON COLUMN documents.ingested_at IS '入库时间。';
COMMENT ON COLUMN documents.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN documents.version IS '版本号。';
COMMENT ON COLUMN documents.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN documents.created_at IS '记录创建时间。';

-- Calendar events may be market-wide or instrument-specific, so the uniqueness rule uses
-- NULLS NOT DISTINCT to treat missing instrument_id as part of the business key.
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    instrument_id BIGINT REFERENCES instruments(id),
    event_type TEXT NOT NULL,
    event_title TEXT NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    region_code TEXT,
    importance_level TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_calendar_events_business_key UNIQUE NULLS NOT DISTINCT (source_id, instrument_id, event_type, event_time, version)
);

COMMENT ON TABLE calendar_events IS '财经日历事件表，记录财报披露、宏观发布、会议等时间型事件。';
COMMENT ON COLUMN calendar_events.id IS '日历事件主键。';
COMMENT ON COLUMN calendar_events.source_id IS '来源数据源主键。';
COMMENT ON COLUMN calendar_events.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN calendar_events.instrument_id IS '关联标的主键，可为空，表示宏观或市场级事件。';
COMMENT ON COLUMN calendar_events.event_type IS '事件类型，例如 earnings、macro_release、central_bank_meeting。';
COMMENT ON COLUMN calendar_events.event_title IS '事件标题。';
COMMENT ON COLUMN calendar_events.event_time IS '事件发生时间。';
COMMENT ON COLUMN calendar_events.region_code IS '地区或国家代码。';
COMMENT ON COLUMN calendar_events.importance_level IS '重要性等级。';
COMMENT ON COLUMN calendar_events.metadata IS '事件扩展元数据，使用 JSONB 存储。';
COMMENT ON COLUMN calendar_events.ingested_at IS '入库时间。';
COMMENT ON COLUMN calendar_events.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN calendar_events.version IS '版本号。';
COMMENT ON COLUMN calendar_events.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN calendar_events.created_at IS '记录创建时间。';

-- Catalyst events represent structured event extraction output. They can point back to
-- a primary supporting document when one exists, but the relation remains optional in v1.
CREATE TABLE IF NOT EXISTS catalyst_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES data_sources(id),
    batch_id BIGINT REFERENCES ingestion_batches(id),
    instrument_id BIGINT REFERENCES instruments(id),
    primary_document_id BIGINT REFERENCES documents(id),
    event_type TEXT NOT NULL,
    event_title TEXT NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    direction TEXT,
    intensity_score NUMERIC(8, 4),
    confidence_score NUMERIC(8, 4),
    rationale_summary TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    as_of TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    raw_uri TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_catalyst_events_business_key UNIQUE NULLS NOT DISTINCT (source_id, instrument_id, event_type, event_time, version)
);

COMMENT ON TABLE catalyst_events IS '催化剂事件表，记录从新闻、公告、研报等抽取出的结构化事件。';
COMMENT ON COLUMN catalyst_events.id IS '催化剂事件主键。';
COMMENT ON COLUMN catalyst_events.source_id IS '来源数据源主键。';
COMMENT ON COLUMN catalyst_events.batch_id IS '来源入库批次主键。';
COMMENT ON COLUMN catalyst_events.instrument_id IS '关联标的主键，可为空，表示更广义的主题或市场事件。';
COMMENT ON COLUMN catalyst_events.primary_document_id IS '主要支撑文档主键，可为空。';
COMMENT ON COLUMN catalyst_events.event_type IS '事件类型，例如 earnings_surprise、policy_change、rating_change。';
COMMENT ON COLUMN catalyst_events.event_title IS '事件标题。';
COMMENT ON COLUMN catalyst_events.event_time IS '事件发生时间。';
COMMENT ON COLUMN catalyst_events.direction IS '影响方向，例如 positive、negative、neutral。';
COMMENT ON COLUMN catalyst_events.intensity_score IS '影响强度分数。';
COMMENT ON COLUMN catalyst_events.confidence_score IS '抽取或判断置信度分数。';
COMMENT ON COLUMN catalyst_events.rationale_summary IS '事件推理摘要。';
COMMENT ON COLUMN catalyst_events.metadata IS '事件扩展元数据，使用 JSONB 存储。';
COMMENT ON COLUMN catalyst_events.ingested_at IS '入库时间。';
COMMENT ON COLUMN catalyst_events.as_of IS '该条记录对应的业务生效时间或快照时间。';
COMMENT ON COLUMN catalyst_events.version IS '版本号。';
COMMENT ON COLUMN catalyst_events.raw_uri IS '对应原始文件或原始响应的位置。';
COMMENT ON COLUMN catalyst_events.created_at IS '记录创建时间。';

CREATE INDEX IF NOT EXISTS idx_ingestion_batches_source_id_started_at
    ON ingestion_batches (source_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_quality_checks_batch_id
    ON quality_checks (batch_id);

CREATE INDEX IF NOT EXISTS idx_instruments_source_id
    ON instruments (source_id);

CREATE INDEX IF NOT EXISTS idx_market_bars_instrument_time
    ON market_bars (instrument_id, bar_time DESC);

CREATE INDEX IF NOT EXISTS idx_market_bars_source_id
    ON market_bars (source_id);

CREATE INDEX IF NOT EXISTS idx_financial_reports_instrument_period
    ON financial_reports (instrument_id, report_period_end DESC);

CREATE INDEX IF NOT EXISTS idx_macro_observations_series_time
    ON macro_observations (series_id, observation_time DESC);

CREATE INDEX IF NOT EXISTS idx_documents_instrument_published_at
    ON documents (instrument_id, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_documents_document_type
    ON documents (document_type);

-- Partial unique indexes avoid forcing NULL-bearing rows into one artificial uniqueness
-- rule while still preventing duplicate documents once an external identifier or URL exists.
CREATE UNIQUE INDEX IF NOT EXISTS uq_documents_source_external_id_version
    ON documents (source_id, external_id, version)
    WHERE external_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_documents_source_url_version
    ON documents (source_id, source_url, version)
    WHERE source_url IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_calendar_events_time
    ON calendar_events (event_time DESC);

CREATE INDEX IF NOT EXISTS idx_catalyst_events_instrument_time
    ON catalyst_events (instrument_id, event_time DESC);

COMMIT;
